### ISSUE TITLE
Any plan to release the dataset?

### ISSUE THREAD

**Issue by ashmalvayani** [FreedomIntelligence/AceGPT#10]
Hello. Thanks for your amazing work. Do you have any plans for releasing both the pre-training dataset (the entire 30B and 10B respectively for 7B and 13B models) and fine-tuning dataset (especially Quora-Arabic)? If they're already available, can you please attach a link to it?

**Comment by wabyking** [comment]
https://huggingface.co/datasets/FreedomIntelligence/Quora-Arabic-GPT4
https://huggingface.co/datasets/FreedomIntelligence/Quora-Arabic-GPT4
https://huggingface.co/datasets/FreedomIntelligence/Code-Alpaca-Arabic-GPT4

Please see the above links, we just make it public.
