### ISSUE TITLE
Missed requirement in requirements.txt

### ISSUE THREAD

**Issue by Mohammed-Deifallah** [FreedomIntelligence/AceGPT#4]
Hi everyone,
After installing all required libraries and packages from `requirements.txt`, I found that there's still something missed, which is "gradio".
I had to add "gradio" to `requirements.txt`.
Kindly, add it to the file for future users.

**Comment by hhwer** [comment]
Thanks for the reminder, it has been added to requirements.

**Comment by Mohammed-Deifallah** [comment]
@hhwer First, thank you for your response. Kindly note that "accelerate" also needs to be added to the `requirements.txt`.
